### ISSUE TITLE
File not found errors for instrumentation and pattern

### ISSUE THREAD

**Issue by eliasreid** [jonasrmichel/rudiments#1]
When trying out the examples, I noticed that when the instrumentation or pattern file is misspelled, the error message was not very useful. In the parse methods, the file is attempted to be opened with `File::open(p)?;`, but that error doesn't print out the path that wasn't found. 

I'm new to rust, but my suggestion would be to add `if !p.is_file() {
            return Err(FileDoesNotExistError(p.into()));
        }` before the call to `File::open(p)?`, which let's us use the FileDoesNotExists error that's already defined in error.rs.

> cargo run -- --pattern ./assets/patterns/standard --instrumentation ./assets/instrumentations/lindrum --samples ./assets/samples/linndrum --tempo 140 --repeat
> 
> Error: IOError(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })
> error: process didn't exit successfully: `target\debug\rudiments.exe --pattern ./assets/patterns/standard --instrumentation ./assets/instrumentations/lindrum --samples ./assets/samples/linndrum --tempo 140 --repeat` (exit code: 1)

Using custom `Error` enum as suggested, output becomes:

> Error: FileDoesNotExistError("./assets/instrumentations/lindrum")
> error: process didn't exit successfully: `target\debug\rudiments.exe --pattern ./assets/patterns/standard --instrumentation ./assets/instrumentations/lindrum --samples ./assets/samples/linndrum --tempo 140 --repeat` (exit code: 1)

**Comment by jonasrmichel** [comment]
Closed by https://github.com/jonasrmichel/rudiments/pull/2.
